name: Build theme

on:
  push:
    branches:
      - "main"

jobs:
  release:
    name: Build release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install npm dependencies
        run: npm i

      - name: Run build
        run: npm run build

      - name: Commit update
        uses: EndBug/add-and-commit@v6
        with:
          branch: release
          message: "ci: build release"
          author_name: deploy-bot
          author_email: deploy-bot@example.com
